# Competition Secretary

Email: [competitionsecretary@alnwickdolphins.com](mailto:competitionsecretary@alnwickdolphins.com)

Alnwick Dolphins is a competitive amateur club. 
We attend a whole range of competitions across the region, and host our own
fixtures at [Willowburn pool](https://www.placesleisure.org/centres/willowburn-sports-and-leisure-centre/).
The competition secretary is responsible for maintaining the competition calendar.

The competition secretary gathers the relevant information, when available, for
away events and adds them to Swim Manager, which is the platform that allows 
swimmers to enter events and pay their fees.
This role is also responsible for communicating with the club to advertise
upcoming events and to ensure everyone knows the opportunities that exist.

The swimming competition year runs from Autumn to Spring.

## Key Responsibilities

- Booking pools for home galas
- Setting up galas (home and away) on Swim Manager
- Arranging licensing of home galas with Swim England
- Liaising with the treasurer to ensure entry payments are correct
- Communicating with the club about upcoming gala opportunities
- Take part in Committee meetings

[Swim England role profile](https://www.swimming.org/library/documents/2061/download)