# Fundraising Coordinator

Raising funds to support our club is really crucial.
The Fundraising Coordinator provides a central point of contact for fundraising 
queries and takes the lead on developing opportunities for accessing grants and funding.
Funds raised go towards providing all the kit necessary to give our swimmers the
best experience and support we can, travel and related expenses, and funding training for
new officials. 

Successful fundraising also means that we can control the fees charged to the 
swimmers, so that being an Alnwick Dolphin is available to as wide a group as
possible.

This is an exciting and fundamental role. 
Impact on the club will be determined by your own motivations and enthusiasm. 
As well as your ability to source funding opportunities, it is an opportunity to 
impact the growth and development of your club.

No knolwedge of swimming is necessary.

## Key Responsibilities
- Identifying new and ongoing sources of funding and sponsorship
- Preparing funding bids in partnership with club committee members as appropriate
- To establish and develop effective working relationships with key local funding providers

[Swim England role profile](https://www.swimming.org/library/documents/127/download)