# Gala Roles {#sec-gala-roles}

For galas hosted by Alnwick Dolphins, we need a team of people willing to put time
into helping organise and staff the event.
On Swim Manager there is the facility to sign up to the different roles for a 
specific gala - there is no requirement to fulfill that role for more than one
gala, or for all days of multi-day galas (but obvioulsy it is easier to manage 
an event if the volunteers are the same on all days).

You don't need to be in any other named role to help with a home gala - sign up 
as you see fit!

The small (but crucial!) volunteer roles that are generally needed and change 
each time are:

## Gala-specific Roles

- Lead organiser

This person takes responsibility for ensuring the [gala checklist](gala-checklist.qmd) is
completed on time for their gala. 
They ensure each named and unnamed role is filled as needed, and often also perform the
role of Runner on the day. 
Each gala has its own Lead Organiser, and the role benefits from strong organisational
and timekeeping skills.
The organisation of a gala starts months before, so the time needed to perform
this role is more than some other. 

- Ticket sales

To be physically present on the day and manage selling spectator tickets.

- Raffle stand

To be physically present on the day and manage the raffle of donated goods.

- Medal table

Manage the medals to be presented on gala day, ensuring there are enough of
each type and that each swimmer receives the correct medal.

- Runners

Ensure information flows as needed between all officials, medal table staff and
team managers as needed.

- Announcer

Use the sound system to announce all the events and housekeeping info on the day.

- Set-up staff

On the day of a gala (or the night before, dependent on timings) we need a small
army of volunteers to help set up the timing equipment, chairs, signage, tables etc.
We also then need to tidy it all away at the end!
The Lead Organiser for a home gala will advise you of when the set up and tidying 
up will take place.

Typically, those people who are already volunteering in other roles also assist
with this work, since they are going to be present on the day anyway.
However, if you'd like to offer to help with this for any particular home gala,
either sign up on Swim Manager, or contact the [Competition Secretary](mailto:competitionsecretary@alnwickdolphins.com).
They can put you in touch with the gala's lead organiser who can assist you to 
find a way to contribute.

## Multi-Gala Roles

- [Team Managers](team-manager.qmd)

To host galas, we also need a whole set of Officials of various types - these are
really important roles that are essential for hosting our own galas, but they
do require a bigger commitment from volunteers.
Please have a look at the Officials page for more information.

- [Officials](official.qmd)



