# Welcome to the Alnwick Dolphins Volunteer Team! {.unnumbered}

Thank you for volunteering with Alnwick Dolphins. 

Our swimming club cannot run without people who are willing to give their time, 
skills and energy to support swimmers.

Some volunteers will be visible on poolside. 
Others will work behind the scenes. 
Some will volunteer every week; others may help at occasional competitions or 
events.

**Every contribution matters.**

You do not need to be an experienced swimmer to volunteer.

You do not need to know all the rules.

You do not need to have volunteered before.

What matters is that you are willing to learn, work as part of a team and put 
the welfare and development of our swimmers at the centre of what you do.

This manual explains how volunteering at Alnwick Dolphins works and provides 
practical guidance for volunteers.

It should be read alongside the club's formal policies and procedures.

## How do I sign up for a role, or find out more?

You can talk to your swimmer's coach, or contact us at [chair@alnwickdolphins.com](mailto:chair@alnwickdolphins.com).
You will receive occasional emails from the club inviting you to sign up for
sporadic volunteering opportunities - please do respond to these if you can!

When the club hosts its own events at Willowburn, its all hands on deck!
There are lots of volunteering jobs needed to help an event run smoothly.
Take a look at the [Gala Roles](#sec-gala-roles) section for some options.
When home galas are added to Swim Manager, various Jobs will be available to sign
up for via the portal - if you're unsure, just speak to any member of the 
coaching squad or committee.

Read on to find out about each type of role.