# Officials

A British Swimming Official is a voluntary role. 
To become an Official, you do not need any prior experience, or swimming knowledge.
We always need to have new Officials coming through because swims cannot be 
recorded with Swim England if the right number of each type of Official is present
at our events, otherwise the swimmers' times cannot be used to enter certain 
competitions.

Each of the following Official roles require a volunteer to commit to undertake
(and keep up to date) relevant training and certification.
They are listed in order of completion, so you must become a Timekeeper before
you can become a Level 1 judge, for example.
Which events they volunteer to help at is, however, up to them. 
Being a registered Official does not mandate you beign available for every event!
The more Officials we have, the less each will need to do to cover our home galas.


- **Timekeepers** 
This is the entry level of roles for swimming officials. 
It requires you to complete a short course of [official training](https://www.britishswimming.org/browse-sport/swimming/officials/officials-qualifications-training/) and be at least 14 years old.


- **Judges**
Judges are people who have completed the [Institute of Swimming](www.swimming.org/ios/courses-officials-volunteers/) training within a time limit of 11 months to receive their judging license (valid for 4 years).
There are thee levels of judges. 
Level 1 is the lowest (entry) level judge.
Level 2 judges require to have completed  over 20 hours of level 1 judging duties
alongside completing additional training. They must be over 15.
Level 2S (Starter) is the highest judge level. 
This is for volunteers who have progressed through levels 1 and 2 and wish to 
qualify as an official Starter.
They need to have completed at least 20 hours of Level 2 judging and additional
training.

- **Starters**
Once a Level 2 judge has completed a minimum of 20 hours of post qualification
experience they are eligible to undertake training to become an official Starter.

- **Referee**
A qualified individual (at least 20 years old) who has passed through the training 
pathway from basic timekeeper to judge to referee. Experience, training and 
mentoring are required to become a referee.
You also need to pass an examination to qualify. 
If interested in finding out more, see [Aquatics GB](https://www.britishswimming.org/browse-sport/swimming/officials/officials-qualifications-training/) or speak to a member of the [Committee](committee_roles.qmd).
