# Parent/Carer Representatives 

Email:

- [lowersquads@alnwickdolphins.com](mailto:lowersquads@alnwickdolphins.com)
- [uppersquads@alnwickdolphins.com](mailto:)

We typically have two parent/carer representatives: one for the Teaching squad
and one for the Upper squad.
Alnwick Dolphins recognises that the club wouldn't exist without the ongoing
support and dedication of the people behind the swimmers!
The representatives are there to ensure parents/carers have a voice in how the
club is run, and in making people feel welcome.


## Key Responsibilities

- Attend Committee meetings
- Be the main point of contact for parents/carers (especially welcoming new ones)
- Support parents/carers entering their swimmers in events
- Be present at key training sessions to meet and welcome new families
- Handing out new uniform and answering question relating to uniform. 


For the lower squad parent representative specifically, this  involves: 

- Processing the new requests as they come in. 
- Liaising with coaches to confirm trial dates. 
- Liaising with the Chairperson or Head Coach if an unusual request comes in. 
- Sending emails out to requestors offering a place on the taster session. 
- Following up any of those who were not successful to invite to the next taster session. 
- Updating the Google spreadsheet to ensure that the correct information is held. 
- Meeting and greeting at the trials
- Liaising with the upper squad representative

[Swim England role profile](https://www.swimming.org/library/documents/4227/download)