# Team Manager

We need volunteers to act as team managers for both home and away galas.
The Team Manager can be thought of as acting like a teacher taking their class
on a school trip. 
Team Managers are responsible for ensuring that teams reach competitions safely 
and that athletes are cared for whilst at events.

They ensure that all swimmers are present and correct, get to where they need to
be during the event, and act as a point of contact for parents/carers to ensure
everybody has all relevant gala information.
They play a crucial role in looking after all swimmers, and they take a lead on
creating away gala itineraries, organising travel and timings, team kit etc.
They should be a person capable of being calm under pressure and maintaining
a positive team spirit which ensures our club is viewed positively whereever we go!

Often, the same people volunteer repeatedly to act as team managers, but it is
important that we bring in new volunteers to the role, since if we cannot supply
a team manager, our swimmers cannot attend away galas.

You will need an up to date DBS check, but no prior experience.

Training is available through two modules provided by Swim England and run 
regionally. You can find further details [here](https://www.swimming.org/careers/volunteer-training-development/).
Alnwick Dolphins typically covers the full cost of this training through its
[Institute of Swimming](https://instituteofswimming.org/) vouchers.
Because of this, we expect a Team Manager to stay in the role for at least one year.

To find out more about becoming a team manager, speak to the club's [Workforce Coordinator]()
or the [Club Secretary](mailto:secretary@alnwickdolphins.co.uk).
 
[Swim England role profile](https://www.swimming.org/library/documents/129/download)