# Welfare Officer

This role is essential in providing a first point of contact for children, parents 
and adults within the club who have a safeguarding or welfare concern.
This person is the advocate for the swimmers, and consequently stays somewhat
appart from the Committee and other long term roles.
Their responsibility is to act independently and in the best interests of an 
athlete at the club, putting their needs above that of others and the club itself.

## Key Responsibilities

- Ensure the club implements [Wavepower](https://www.swimming.org/swimengland/wavepower-child-safeguarding-for-clubs/),
Swim England's safeguarding policy and procedures correctly. 
- Be the first point of contact for all staff, volunteers, swimmers and their
parents/carers for any issues concerning welfare, poor practice or potential or 
alleged abuse.
- To ensure that all incidents are reported correctly and referred, in accordance 
with Wavepower.
- Ensuring relevant roles have up to date DBS checks and safeguarding training.

## Requirements
- Current DBS certification
- Training:

## [Swim England role profile](https://www.swimming.org/library/documents/132/download)
