# Workforce Coordinator

Email: [workforce@alnwickdolphins.com](mailto:workforce@alnwickdolphins.com)

Do we have enough Officials?
Do we have the right mix of skills in the volunteers?
Do we have who we need to be able to host galas?
Are our volunteers armed with all the infomation and support they need?

Answering all these questions and more falls to the role of the workforce
coordinator.
They hold a key position on the committee, since the club would not exist without
a healthy supply of well prepared volunteers!

## Key Responsibilities

- Retaining and recruiting new volunteers throughout all of the roles within the club (committee, coaches, team managers, poolside helpers, officials).
- Co-ordinating volunteers to ensure adequate cover is provided during galas home and away.
- Ensuring that volunteers have the appropriate qualifications to enable them to continue in their role.
- Identifying the future needs of the club in respect of positions that may become vacant in the future.

## Requirements

- Good and effective communications skills
- Some knowledge of the gala pyramid to ensure cover is provided
- Knowledge of the requirements by either the Club or Swim England to enable volunteers to be poolside.